/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'app-bg': 'var(--app-bg)',
        'sidebar-bg': 'var(--sidebar-bg)',
        'main-bg': 'var(--main-bg)',
        'panel-bg': 'var(--panel-bg)',
        border: 'var(--border)',
        'border-subtle': 'var(--border-subtle)',
        'input-bg': 'var(--input-bg)',
        'input-border': 'var(--input-border)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        muted: 'var(--text-muted)',
        'text-faint': 'var(--text-faint)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-bg-tint': 'var(--accent-bg-tint)',
        'accent-focus-ring': 'var(--accent-focus-ring)',
        'btn-secondary-bg': 'var(--btn-secondary-bg)',
        'btn-secondary-text': 'var(--btn-secondary-text)',
        'btn-primary-text': 'var(--btn-primary-text)',
        'hover-bg': 'var(--hover-bg)',
        'active-bg': 'var(--active-bg)',
        success: 'var(--success)',
        'success-bg': 'var(--success-bg)',
        danger: 'var(--danger)',
        'badge-pro-bg': 'var(--badge-pro-bg)',
        'badge-pro-text': 'var(--badge-pro-text)',
        'badge-soon-bg': 'var(--badge-soon-bg)',
        'badge-soon-text': 'var(--badge-soon-text)',
        'dropzone-bg': 'var(--dropzone-bg)',
        'dropzone-border': 'var(--dropzone-border)',
        'swatch-border': 'var(--swatch-border)',
        'titlebar-bg': 'var(--titlebar-bg)',
        'statusbar-bg': 'var(--statusbar-bg)',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'monospace'],
      },
      borderRadius: {
        sm: '2px',
      },
    },
  },
  plugins: [],
}
